### ISSUE TITLE
Deadlocking on removeAllObjects and removeExpiredObjects

### ISSUE THREAD

**Issue by incognitosoftware1** [aschuch/AwesomeCache#10]
Calling removeAllObjects and removeExpiredObjects causes a deadlock

The issue happens since they call dispatch_async on the diskQueue, and that closure calls dispatch_sync on the same queue. That first closure never returns due to dispatch_sync blocking. Deadlock :(

The easiest fix is for these methods to call dispatch_async on a different queue.

**Comment by aschuch** [comment]
Thanks for discovering. 
Do you want to submit a fix?

**Comment by incognitosoftware1** [comment]
To be honest, I'm not sure how. I am the sole developer on my projects and don't know how to use shared source control systems like github for anything more than browsing.

Here's how I fixed it:

Added at line 35: 
    `private let otherQueue: dispatch_queue_t = dispatch_queue_create("com.aschuch.cache.otherQueue", DISPATCH_QUEUE_SERIAL)`
and referenced that queue in the aforementioned methods at lines 209 and 227

Sorry I can't make the submission more formal
