### ISSUE TITLE
Cache is empty when application quit and run background

### ISSUE THREAD

**Issue by Persilos** [aschuch/AwesomeCache#13]
Hi ! 
I have a class "CacheUtilities" i use it for stock a Static Cache of UIImage.
I have a lot of image to load from my server, so i want load it just one time and keep it on my Cache (except if user close the process of my app ! )

But i have a problem, when the user only close my app (not kill the app, just quit and make it run in background) and come back, my Cache is empty and i need to reload all images... What's the solution ? 

I use the expires .Never

CacheUtilities.getCacheImage().setObject(UIImage(data: data)!, forKey: sUrl, expires: CacheExpiry.Never)

**Comment by alenofx** [comment]
Disk write will silently fail when the key contains characters not compatible with the filesystem (it's used as filename); this is the case of URLs.

I've fixed this problem cleaning up the key using a regex solution like: http://stackoverflow.com/questions/6102333/what-characters-are-allowed-in-a-ios-file-name/18526106#18526106

**Comment by aschuch** [comment]
I think AwesomeCache should make sure to escape the `name` before saving.
E.g. here: https://github.com/aschuch/AwesomeCache/blob/master/AwesomeCache/Cache.swift#L255

**Comment by aschuch** [comment]
I have just authored version `1.0.2` of AwesomeCache that should fix this issue.
