### ISSUE TITLE
Thanks for this!

### ISSUE THREAD

**Issue by nickoneill** [aschuch/AwesomeCache#17]
I was previously using Haneke Swift for caching but between mystery crashes and general lack of updates I've been looking for something to replace it.

I just replaced all my Haneke code with AwesomeCache and I'm really liking it so far. The API for AwesomeCache is much more straightforward and I was able to simplify a fairly complex Haneke flow for  something I like much better! In particular the Awesome API Caching is aptly named!

The only thing I miss is the UIImageView category to easily set images in a shared image cache but I'm sure that'll appear eventually, I may even hack on something this weekend.

Anyway, thanks!

**Comment by aschuch** [comment]
Thanks, really appreciate your feedback.

I have not yet had the time to properly think about a `UIImageView` category, but I'd be looking forward to a PR in case you want to hack on it.
