### ISSUE TITLE
AwesomeCache does not build Swift 1.2 as default. 

### ISSUE THREAD

**Issue by pfitz** [aschuch/AwesomeCache#18]
I just inserted 

```
github "aschuch/AwesomeCache" 
```
into my ```Cartfile``` and did a ```carthage update```. Carthage did not installed  the current master as default but the last tagged Version which is the Swift 1.1 Tag.

```
*** Checking out AwesomeCache at "swift-1.1"
```

changing the Cartfile to 

    github "aschuch/AwesomeCache" "master"

checked out the master branch. 

And the ```Swift-1.1``` tag does not build at my environment at all. I get the following error messages:

```
2015-06-03 10:04:31.213 xcodebuild[3478:43851] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path 'Patoh to Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
```

**Comment by aschuch** [comment]
This is related to an issue in carthage, tracked as https://github.com/Carthage/Carthage/issues/469

**Comment by pfitz** [comment]
Ok. Thanks for the Cache by the way. Works great!

**Comment by aschuch** [comment]
Ok, I have removed the swift-1.1 as it was causing so many problems.

**Comment by pfitz** [comment]
:+1:
