### ISSUE TITLE
How do we cache API calls?

### ISSUE THREAD

**Issue by darer** [aschuch/AwesomeCache#24]
Hi. I want to say that AwesomeCache has been really helpful so far with caching images. I'm kinda new to programming and now I have to deal with APIs. I see that we can use this to cache the API calls but I don't understand how to declare the cache.

    let cache = Cache<UIImage>(name: "awesomeCache")

What do I put instead of UIImage? I'm using Alamofire and SwiftyJSON to make the request and then read it. In what format can I cache the response? Is it possible to cache the JSON object?

Thanks in advance!

**Comment by MMasterson** [comment]
Hey @darer - I usually store JSON objects as an NSDictionary  with AwesomeCache
