### ISSUE TITLE
Remove object synchronously 

### ISSUE THREAD

**Issue by namanhams** [aschuch/AwesomeCache#33]
I think it's good if we have an option to remove/clear objects synchronously. 
The scenario is that i know the cache is no longer valid and i want to make sure that i don't fetch from it until i completely remove all objects.

**Comment by irace** [comment]
You could do implement this in user-space using a semaphore or dispatch group, no?

**Comment by namanhams** [comment]
You can't. The function to remove/clear objects itself is asynchronous, it will return immediately. It's no point calling that function with a semaphore or distpatch_sync.

**Comment by irace** [comment]
Ah, sorry. Did not realize there was not even a completion block.

**Comment by aschuch** [comment]
@namanhams Do you think a completion block would be sufficient? I am not sure if I want to add sync methods for everything, since that would make the API much larger and more difficult to understand. Since the async part is backed by a serial queue, you should be able to call `removeObject` and `setObject` immediately after each other and the queue would make sure to first remove then add the object.

**Comment by namanhams** [comment]
@aschuch : i think adding a completion block would be good enough. Actually i prefer this over a separate sync methods.

**Comment by irace** [comment]
One thing worth considering (and we experienced this with [TMCache](https://github.com/tumblr/TMCache)) is that while async by default with the ability to make synchronous using semaphores or dispatch groups seems like a great idea on paper, it ends up using more threads than synchronous by default with the ability to make _asynchronous_ when needed does. Just food for thought.

**Comment by namanhams** [comment]
Actually @irace  is right. Make the methods synchronous and wrap it with asynchronous when needed is much easier. That's what i usually do as well

**Comment by aschuch** [comment]
Please take a look at the WIP draft for AwesomeCache 3.0 #56, which will move towards a sync only API as suggested by @irace and @namanhams. Let me know what you think.
