### ISSUE TITLE
when support swift2.0 ?

### ISSUE THREAD

**Issue by lacklock** [aschuch/AwesomeCache#37]
%>_<%

**Comment by CVertex** [comment]
yeah, when ?

**Comment by aschuch** [comment]
You can already use the `two-oh` branch for swift 2.

**Comment by CVertex** [comment]
Thanks! I'll give this a go

**Comment by aschuch** [comment]
No problem. Looking forward to your feedback. As soon as I get some confirmation that everything works, I am happy to merge the branch.

**Comment by aschuch** [comment]
I have just released AwesomeCache 2.0. Enjoy!
