### ISSUE TITLE
Retrieving an image from Cache raises an exception.

### ISSUE THREAD

**Issue by dziedziela** [aschuch/AwesomeCache#40]
![screen shot 2015-10-26 at 15 59 40](https://cloud.githubusercontent.com/assets/2911850/10734356/d32de3f4-7bfa-11e5-9b86-fbb97a37d92c.png)
![screen shot 2015-10-26 at 15 59 48](https://cloud.githubusercontent.com/assets/2911850/10734357/d32fe082-7bfa-11e5-9930-1f0dcf4c45fb.png)

**Comment by aschuch** [comment]
Please take a look at the PR I've just opened.

**Comment by dziedziela** [comment]
PR?

**Comment by aschuch** [comment]
The Pull Request #41 referenced above.
