### ISSUE TITLE
Huge cache size

### ISSUE THREAD

**Issue by MattesGroeger** [aschuch/AwesomeCache#45]
We are using AwesomeCache and it's great. 

Now I implemented it for some bigger images and suddenly noticed a crazy amount of disk usage. 

A picture with 414kb takes up almost 5MB on disk (`Caches/com.aschuch.cache/images/xxx.cache`). Is this something expected?

Help would be much appreciated!

**Comment by aschuch** [comment]
Hm, this indeed sounds a bit strange. I've not experienced this.
AwesomeCache uses `NSCoding` and `NSKeyedArchiver` to persist objects under the hood.

Could you try and persist the picture using `NSKeyedArchiver` to try and see if the persisted object is of similar size?

**Comment by MattesGroeger** [comment]
I'll try that tomorrow. 

When I inspected the cached binary I saw `NSKeyedArchiver` annotations already. Maybe this problem is also specific to JPEG files. Will investigate further tomorrow.

**Comment by mbuchetics** [comment]
`NSKeyedArchiver` will persist the uncompressed `UIImage` and that's why you see the difference in size compared to the JPEG file. You would need to cache the data returned by `
UIImageJPEGRepresentation`.

**Comment by MattesGroeger** [comment]
@mbuchetics Good point! Thanks a lot, that makes sense and I just changed our implementation accordingly:

Use `NSData` as cached type:
```
struct Images {
    static let cache = Cache<NSData>(name: "images")
}
```

Writing to cache:
```
if let data = UIImageJPEGRepresentation(processedImage, 0.6) {
    Images.cache.setObject(data,
        forKey: imageId,
        expires: cacheExpiry)
}
```

Reading from cache:
```
if let imageData = Images.cache[imageId] {
    return UIImage(data: imageData)
}
```

Now file sizes are under 1MB. Issue can be closed then. Keep up the good work!

**Comment by aschuch** [comment]
@mbuchetics Thanks for the clarification.

@MattesGroeger Awesome, if you have further questions feel free to reopen. :sparkler:
