### ISSUE TITLE
Suggest to add hash function for cannot save cache to disk with long filename

### ISSUE THREAD

**Issue by ivanip** [aschuch/AwesomeCache#5]
Because of the limitation of filename in IOS and we use http url as key in many time,  it is easily hit the the limitation. Suggest to use hash as the key in setObject().

**Comment by aschuch** [comment]
Can you give me an example for the input and the error that is thrown?

**Comment by aschuch** [comment]
Hi @ivanip, I am closing this now, as I haven't heard back from you in a while.
