### ISSUE TITLE
setObject without closures is internal

### ISSUE THREAD

**Issue by aloco** [aschuch/AwesomeCache#57]
Hi is there a reason you removed https://github.com/aschuch/AwesomeCache/blob/master/AwesomeCache/Cache.swift#L144-L146 from the new "three" branch? Always used this method. I can only find https://github.com/aschuch/AwesomeCache/blob/three/AwesomeCache/Cache.swift#L141-L154 which is marked as `internal`

**Comment by aschuch** [comment]
That's an oversight on my part. Will push an update shortly.
