### ISSUE TITLE
removeExpiredObjects deadlocks

### ISSUE THREAD

**Issue by aloco** [aschuch/AwesomeCache#58]
Hi, currently `removeExpiredObjects` deadlocks, caused by 2 nested `dispatch_sync(queue)`.

I think we have to move `keys.forEach { self.objectForKey($0) }` outside the dispatch call since `objectForKey` will dispatch on the queue anyway.

https://github.com/aschuch/AwesomeCache/blob/three/AwesomeCache/Cache.swift#L193

**Comment by aschuch** [comment]
I've fixed this issue in 544b35c91e9333f61983b4b8af2d45d9d681f71f, please take a look :sparkler:
