### ISSUE TITLE
watchOS Support

### ISSUE THREAD

**Issue by spenceratkin** [aschuch/AwesomeCache#60]
When running `pod install`, Cocoapods shows the error
```
[!] The platform of the target 'TJIntranetWatch Extension' (watchOS 2.0) is not compatible with
'AwesomeCache (2.0)', which does not support 'watchos'.
```

Does AwesomeCache not support watchOS, or is there something missing from the Podspec?

**Comment by aschuch** [comment]
AwesomeCache does support watchos, I guess its just missing in the podspec.
