### ISSUE TITLE
iPhone 4 with iOS 7.1 crash EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by littner** [aschuch/AwesomeCache#63]
` var cache = try! Cache<NSString>(name: "cache")`

The app  always crashes on this line. Only EXC_BAD_ACCESS. Nothing more.

Tried setting breakpoints in Cache class itself, could not reach them

**Comment by littner** [comment]
Well, it actually happens on any iPhone I've tested....

**Comment by aschuch** [comment]
Unfortunately, AwesomeCache does not support iOS < 8, since it is using iOS 8 APIs.
