### ISSUE TITLE
How to use cache my Class?

### ISSUE THREAD

**Issue by conloyal** [aschuch/AwesomeCache#69]
Hi,
How to use cache with my class?
I saved "my name" cache then get name from cache. It is incorrect. 
Please help me.
Thanks, Huy.

EX:
class myclass : NSObject, NSCoding {
  private var _name:String = ""
  func setName(name:String) { self._name = name } 
  func getName() -> String { return self._name }
  override init() {}
  required init(coder aDecoder: NSCoder) {   }
  func encodeWithCoder(_aCoder: NSCoder) {   }
}

MyViewController
let KEY_CACHE = "myapp"
do {
      let cache = try Cache<myclass>(name: KEY_CACHE)
      if let rs = cache.objectForKey("test") {
          log( " --------- Loaded ------------- ")
          let name = rs.getName()           //Incorrect: Name is empty.
      } else {
        log( " --------- Nil  ------------- ")
        let x:myclass = myclass()
        x.setName("my name")
        cache.setObject(x, forKey: "test")
      }
    } catch {
      
    }

**Comment by aschuch** [comment]
You have to implement the methods of the `NSCoding` protocol. [Here](http://nshipster.com/nscoding/) is a good tutorial on `NSCoding` in general.
