### ISSUE TITLE
Please add support to iOS 7.1 in Podspec file

### ISSUE THREAD

**Issue by fernandodev** [aschuch/AwesomeCache#7]

**Comment by aschuch** [comment]
Can you confirm everything is working with iOS 7.1? I haven't had the chance to fully test it with versions previous to 8.0.

**Comment by aschuch** [comment]
@fernandodev any updates on this?

**Comment by fernandodev** [comment]
@aschuch sorry for I don't answer you before, I was totally busy. But I've good news. I'm using in a project (iOS >= 7.1) and It works fine. So, I'm doing a sample test for your lib and when I finish, brace yourself, PR will come in. ;D
