### ISSUE TITLE
Unresolved Identifier in Cache.swift File

### ISSUE THREAD

**Issue by jdulb17** [aschuch/AwesomeCache#76]
Hello, I installed AwesomeCache into my Xcode project through the manual installation method; however, when I attempt to run my program, there is an error in the Cache.swift file that says " Use of unresolved identifier '_awesomeCache_unarchiveObjectSafely' " (Line 235 in the file). Is there a fix for this or is this possibly an issue that resulted from using the manual installation? Thanks!

**Comment by aschuch** [comment]
This is an error in the documentation. Besides the two Swift files, you'd also need to add the `NSKeyedUnarchiverWrapper.h/.m` files to your project. I'll keep this issue open and add better documentation for manual installation soon.

**Comment by ferologics** [comment]
bump

**Comment by ClearerMe** [comment]
@jdulb17 , @aschuch , In addition to these, you need create a swift-ObjectiveC-bridging file, and in this file, you need import  
NSKeyedUnarchiverWrapper.h. Binggo, it works

**Comment by ClearerMe** [comment]
@jdulb17 , @aschuch , In addition to these, you need create a swift-ObjectiveC-bridging file, and in this file, you need import NSKeyedUnarchiverWrapper.h file.  Binggo, it works~

**Comment by aschuch** [comment]
Thanks everyone. I've added this info to the Readme.
