### ISSUE TITLE
Cache encryption

### ISSUE THREAD

**Issue by netgfx** [aschuch/AwesomeCache#77]
Is there a way to apply encryption to the file saved on the disk?

I know about the data that are stored inside but is there a way to actually encrypt the file?

**Comment by aschuch** [comment]
Please take a look at the [subclassing notes](https://github.com/aschuch/AwesomeCache/blob/master/AwesomeCache/Cache.swift#L14) in `Cache.swift`. I think you could simply subclass the Cache and provide your own means of encryption/decryption before calling super.

**Comment by netgfx** [comment]
I see thanks.
