### ISSUE TITLE
Not working with Swift 3.0

### ISSUE THREAD

**Issue by mobitronics** [aschuch/AwesomeCache#78]
Not compiling with the Swift 3.0. I used Xcode 8.0 default migration tool to convert in Swift 3.0 but still no luck. Please find below error image for reference.

<img width="1524" alt="swift3 0_error" src="https://cloud.githubusercontent.com/assets/11852750/17137646/dd0753d8-5359-11e6-82dd-53cb4d6d6ca0.png">

**Comment by notohiro** [comment]
I need Swift 3.0 version too.
Rewritten here.
https://github.com/notohiro/AwesomeCache/tree/Swift-3.0

Replace NSCache with Dictionary, because of String is no longer confirm AnyObject in Swift 3.0.

**Comment by notohiro** [comment]
Created pull request [here](https://github.com/aschuch/AwesomeCache/pull/81)

**Comment by netgfx** [comment]
Is this issue resolved on `master`?

**Comment by notohiro** [comment]
not yet, but he started working it
https://twitter.com/schuchalexander/status/773974080022274049

**Comment by netgfx** [comment]
Any ETA on this? There is also a PR about Swift 3.0

**Comment by aschuch** [comment]
I am working towards supporting Swift 2.3 and 3.0 for AwesomeCache within the next couple of days. Stay tuned. 💯

**Comment by aschuch** [comment]
The Swift 2.3 version is tagged as `4.0`, master contains a working Swift 3.0 version.

**Comment by phucdoan** [comment]
is master working with Swift 3.0 right now? 
Sorry, but version 3.0.1 not work on me. Did i missed something?
Anyhow, thanks for your effort!

**Comment by aschuch** [comment]
Yes, master is ready for 3.0

**Comment by aschuch** [comment]
I've just released version 5.0 with full Swift 3 support.
