### ISSUE TITLE
why its written swift 3.0 support , when it is not working ????

### ISSUE THREAD

**Issue by aryansbtloe** [aschuch/AwesomeCache#88]
hi guys

i tried it using xcode 8.0 and swift 3.0 , its not working

**Comment by aschuch** [comment]
What is not working exactly? Which installation method did you use?

**Comment by kevinmann** [comment]
I am use Carthage for the install method and I get this error:

```
Carthage/Build/iOS/AwesomeCache.framework/AwesomeCache 
compiled with older version of Swift language (2.0) than previous files (3.0) 
```

I tried both `github "aschuch/AwesomeCache"` and `github "aschuch/AwesomeCache" ~> 4.0`

**Comment by aschuch** [comment]
Please try with `github "aschuch/AwesomeCache" "master"`, since there isn't a release for Swift 3.0 yet.

**Comment by kevinmann** [comment]
That worked perfectly thank you.
