### ISSUE TITLE
Error - Version 3.0.1 is Swift 2.3

### ISSUE THREAD

**Issue by cristinaITdeveloper** [aschuch/AwesomeCache#91]
I have update the library with last version, but there are more error in the code. 
See screenshot:

<img width="930" alt="schermata 2016-10-22 alle 13 15 41" src="https://cloud.githubusercontent.com/assets/11472348/19618962/c943d746-9859-11e6-8af6-26a8d4c8d9c9.png">

Thank you for support!

**Comment by LadyDeveloper** [comment]
The library isn't in Swift 3, but in Swift 2.3

<img width="1130" alt="schermata 2016-10-22 alle 14 24 55" src="https://cloud.githubusercontent.com/assets/11472348/19619272/761dd0b2-9863-11e6-9246-7a7f080db231.png">

How can I resolve this problem?

**Comment by rushk2112** [comment]
Cristina,
  You can use the "master" branch by changing your Podfile to:
	pod 'AwesomeCache', :git => 'https://github.com/aschuch/AwesomeCache.git', :branch => 'master'

This allowed me tu se the Swift 3.0 version

**Comment by aschuch** [comment]
I've just pushed a new version 5.0 with full Swift 3 support.
